#!/usr/bin/env ruby
#^syntax detection
source 'https://api.berkshelf.com'

cookbook 'yum', '~> 3.3.2'
cookbook 'yum-epel', '~> 0.5.1'
cookbook 'yum-ius', '~> 0.3.0'
cookbook 'mysql', '~> 4.1.2'
cookbook 'php', '~> 1.3.12'
cookbook 'redisio', '~> 1.7.1'
cookbook 'memcached', '~> 1.7.2'
cookbook 'nginx', '2.4.2'
cookbook 'apache2', '~> 1.8.14'
cookbook 'elasticsearch', '~> 0.3.7'
cookbook 'data-bag-merge', '~> 0.1.3'

cookbook 'jetty', :github => 'inviqa/chef-jetty', :tag => '0.2'
cookbook 'solr', :github => 'inviqa/chef-solr', :tag => '1.0.1'
cookbook 'chef-varnish', :github => 'inviqa/chef-varnish', :ref => '2.1.0'
cookbook 'php-fpm', :github => 'inviqa/cookbook-php-fpm', :tag => '0.6.11'
cookbook 'config-driven-helper', '~> 2.5'

cookbook 'project', :path => 'site-cookbooks/project'

# Pin cookbooks to avoid bringing in chef 12+ code
cookbook 'aws', '~> 2.7.2'
cookbook 'dmg', '~> 2.2.2'
cookbook 'homebrew', '~> 1.10.0'
cookbook 'git', '~> 4.2.2'
cookbook 'iis', '~> 4.1.1'
cookbook 'iptables', '~> 1.0.0'
cookbook 'rsyslog', '~> 2.2.0'

# Please try to avoid using anything from these. They may be deprecated soon.
cookbook 'chef-magento', :github => 'inviqa/chef-magento', :tag => '1.1.0'
cookbook 'chef-php-extra', :github => 'inviqa/chef-php-extra', :tag => '0.4.1-legacy-upgrade'
