#!/usr/bin/env ruby
# ^ Syntax hint

require 'hobo/tasks/magento'

namespace :config do
    task :'set-theme' do
        Hobo.ui.success 'Setting session theme'
        vm_shell("bin/n98-magerun.phar config:set design/package/name session", :realtime => true, :indent => 2)
        Hobo.ui.separator
    end
end

task "vm:up" => [
    "tools:n98magerun",
    "config:set-theme",
    "magento:initialize-vm"
]
